spring:
  datasource:
    data: classpath:schema-h2.sql # Spring Session 테이블 스키마 적용
  jpa:
    show-sql: true # JPA로 생성되는 쿼리 확인
    hibernate:
      ddl-auto: create # 프로젝트 시작시 테이블 생성
  h2:
    console:
      enabled: true
      path: /h2-console # h2 db 웹 클라이언트 접속 url
  devtools:
    livereload:
      enabled: true # 정적파일들의 실시간 갱신


#security:
#  basic:
#    enabled: false # security 기본 인증 옵션 제거
logging:
  level:
    org.hibernate.type: trace # JPA로 생성되는 쿼리의 파라미터 값 확인

